[project]
name = "pdf-ingestion-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.65.0",
    "docling-core[chunking-openai]>=2.57.0",
    "fastapi[standard]>=0.126.0",
    "openai>=2.14.0",
    "pydantic-settings>=2.12.0",
]
